### PR TITLE
chore: Bump Go version in mod file

### PR DESCRIPTION
**Pull request by friedrichwilken**
Blocked: https://github.com/kyma-project/eventing-auth-manager/pull/129#issuecomment-1956059555

**Description**

Changes proposed in this pull request:

- Bump the Go version in the mod file to `v1.22.0`.

**Related issue(s)**
none

### CODE REVIEW

**Comment by friedrichwilken** [comment]
It looks like the [Docker-in-Docker image](https://github.com/kyma-project/test-infra/blob/7abd78e0f5af48bc6efd25ef6a3428932df7931d/prow/jobs/kyma-project/eventing-auth-manager/eam-integration-test.yaml#L25C20-L25C102) we use for the `pull-eventing-auth-manager-integration-test` job is outdated and cannot support Go >=`v1.22.0`. So we might need to wait until a newer image is available in the [registry](https://console.cloud.google.com/artifacts/docker/kyma-project/europe/prod/testimages%2Fe2e-dind-k3d).

**Comment by friedrichwilken** [comment]
It looks like the [Docker-in-Docker image](https://github.com/kyma-project/test-infra/blob/7abd78e0f5af48bc6efd25ef6a3428932df7931d/prow/jobs/kyma-project/eventing-auth-manager/eam-integration-test.yaml#L25C20-L25C102) we use for the `pull-eventing-auth-manager-integration-test` job is outdated and cannot support Go >=`v1.22.0`. So we might need to wait until a newer image is available in the [registery](https://console.cloud.google.com/artifacts/docker/kyma-project/europe/prod/testimages%2Fe2e-dind-k3d).

**Comment by k15r** [comment]
> It looks like the [Docker-in-Docker image](https://github.com/kyma-project/test-infra/blob/7abd78e0f5af48bc6efd25ef6a3428932df7931d/prow/jobs/kyma-project/eventing-auth-manager/eam-integration-test.yaml#L25C20-L25C102) we use for the `pull-eventing-auth-manager-integration-test` job is outdated and cannot support Go >=`v1.22.0`. So we might need to wait until a newer image is available in the [registry](https://console.cloud.google.com/artifacts/docker/kyma-project/europe/prod/testimages%2Fe2e-dind-k3d).

maybe this here fixes the situation: https://github.com/kyma-project/eventing-auth-manager/pull/131

**Review by mfaizanse — APPROVED** [review]

**Pull request merged**
